version: '3'

volumes:
  mariadb_data:

services:
  web:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./docker/web/conf.d/app.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www:cached

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/var/www:delegated
      - ./docker/app/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      LANG: C.UTF-8
      DISABLE_IP_PROTECTION: 'true'

  mariadb:
    image: mariadb
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql:cached
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  webpack:
    image: node:10-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    expose:
      - 8080
    #command: sh -c 'yarn install && yarn dev'
    command: sh -c 'yarn dev'